apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: exitcam
  namespace: dapr-trafficcontrol
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: rmax1412storage
  - name: storageAccessKey
    secretKeyRef:
      name: StorageQueue-AccessKey
  - name: queue
    value: exitcam
auth:
  secretStore: trafficcontrol-secrets-kv
scopes:
  - trafficcontrolservice
  - simulation